### ISSUE TITLE
랭킹 페이지

### ISSUE THREAD

**Issue by lerrybe** [venture-web-4/venture-norara#9]
Landing 페이지에 넣을까요.....
페이지를 하나 팔까요.... 
고민이 됩니다

당신의 랭킹에게 투표해주세요 ㅜㅡ

1 (Landing에 넣는다)
2 (페이지를 판다)

**Comment by esc5221** [comment]
1에 한표 갑니다

**Comment by lerrybe** [comment]
첫번째 의견 따라가겠습니다 🥳 인생은 선착순
